---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: babylon-reporting-operator deploy
  name: babylon-reporting-operator-build

parameters:
- name: NAME
  value: babylon-reporting-operator
- name: GIT_REPO
  value: https://github.com/redhat-cop/babylon.git
- name: GIT_REF
  value: main
- name: KOPF_S2I_IMAGE
  value: quay.io/redhat-cop/python-kopf-s2i:v1.33

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: reporting-operator
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${KOPF_S2I_IMAGE}
    triggers: []
