{{ if .Values.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "babylon-reporting-operator.name" . }}
  namespace: {{ include "babylon-reporting-operator.namespaceName" . }}
  labels:
    {{- include "babylon-reporting-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "babylon-reporting-operator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "babylon-reporting-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: notifier
        env:
        - name: ANARCHY_DOMAIN
          value: {{ required ".Values.anarchy.domain is required!" .Values.anarchy.domain | quote }}
        - name: BABYLON_DOMAIN
          value: {{ required ".Values.babylon.domain is required!" .Values.babylon.domain | quote }}
        - name: POOLBOY_DOMAIN
          value: {{ required ".Values.poolboy.domain is required!" .Values.poolboy.domain | quote }}
        image: {{ include "babylon-reporting-operator.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "babylon-reporting-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
