{{ if .Values.sfdc }}
apiVersion: v1
kind: Secret
metadata:
  name: gpte-sf-secrets
  namespace: {{ include "babylon-reporting-operator.namespaceName" . }}
  labels:
    {{- include "babylon-reporting-operator.labels" . | nindent 4 }}
type: Opaque
data:
  sf_host: {{ required ".Values.sfdc.host is required!" .Values.sfdc.host | b64enc }}
  sf_username: {{ required ".Values.sfdc.username is required!" .Values.sfdc.username | b64enc }}
  sf_consumer_key: {{ required ".Values.sfdc.consumer_key is required!" .Values.sfdc.consumer_key | b64enc }}
  sf_cert_key: {{ required ".Values.sfdc.key is required!" .Values.sfdc.key | b64enc }}
{{ end }}
