{{ if .Values.ldap }}
apiVersion: v1
kind: Secret
metadata:
  name: gpte-ldap-secrets
  namespace: {{ include "babylon-reporting.namespaceName" . }}
  labels:
    {{- include "babylon-reporting.labels" . | nindent 4 }}
type: Opaque
data:
  ldap_hosts: {{ required ".Values.ldap.hosts is required!" .Values.ldap.hosts | b64enc }}
  binddn: {{ required ".Values.ldap.binddn is required!" .Values.ldap.binddn | b64enc }}
  bindpw: {{ required ".Values.ldap.bindpw is required!" .Values.ldap.bindpw | b64enc }}
  searchattribute: {{ required ".Values.ldap.searchattribute is required!" .Values.ldap.searchattribute | b64enc }}
  basedn: {{ required ".Values.ldap.basedn is required!" .Values.ldap.basedn | b64enc }}
  basedndeleted: {{ required ".Values.ldap.basedndeleted is required!" .Values.ldap.basedndeleted | b64enc }}
{{ end }}
