{{ if .Values.ipa }}
apiVersion: v1
kind: Secret
metadata:
  name: gpte-ipa-secrets
  namespace: {{ include "babylon-reporting-operator.namespaceName" . }}
  labels:
    {{- include "babylon-reporting.labels" . | nindent 4 }}
type: Opaque
data:
  ldap_hosts: {{ required ".Values.ipa.hosts is required!" .Values.ipa.hosts | b64enc }}
  binddn: {{ required ".Values.ipa.binddn is required!" .Values.ipa.binddn | b64enc }}
  bindpw: {{ required ".Values.ipa.bindpw is required!" .Values.ipa.bindpw | b64enc }}
  searchattribute: {{ required ".Values.ipa.searchattribute is required!" .Values.ipa.searchattribute | b64enc }}
  basedn: {{ required ".Values.ipa.basedn is required!" .Values.ipa.basedn | b64enc }}
{{ end }}
