apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "babylon-reporting-operator.name" . }}
  annotations:
    description: >-
      Add access to cluster-reader role for Babylon resources.
  labels:
    {{- include "babylon-reporting-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.babylon.domain }}
  resources:
  - catalogitems
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.poolboy.domain }}
  resources:
  - resourceclaims
  - resourcehandles
  - resourcepools
  - resourceproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.anarchy.domain }}
  resources:
  - anarchyactions
  - anarchygovernors
  - anarchyruns
  - anarchysubjects
  verbs:
  - get
  - list
  - watch

{{ if .Values.deploy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "babylon-reporting-operator.name" . }}
  labels:
    {{- include "babylon-reporting-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "babylon-reporting-operator.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "babylon-reporting-operator.serviceAccountName" . }}
  namespace: {{ include "babylon-reporting-operator.namespaceName" . }}
{{ end }}
