{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babylon-reporting-operator.serviceAccountName" . }}
  namespace: {{ include "babylon-reporting-operator.namespaceName" . }}
  labels:
    {{- include "babylon-reporting-operator.labels" . | nindent 4 }}
{{ end }}
